version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test_regression_model_py36:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/project/packages/regression_model
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run tests with Python 3.6
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py36

workflows:
  version: 2.1
  test-all:
    jobs:
      - test_regression_model_py36
