PATH:
  PROJECT_PATH: D:\Kaggle\MachineLearning_CI_CD
  SCRIPT_PATH: D:\Kaggle\MachineLearning_CI_CD\scripts
  MODELS_PATH: D:\Kaggle\MachineLearning_CI_CD\models
  DATA_PATH: D:\Kaggle\MachineLearning_CI_CD\data